services:
  app:
    image: docker-flask
    build:
      context: ./app
    ports:
      - "8080:8080"
  proxy:
    image: docker-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
